#!/bin/bash

SESSIONNAME="AF_basic"
WORK_DIR="~/code"

tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ] 
 then
     tmux new-session -d -s $SESSIONNAME -n HUD

     # Setup project specific windows and cd into the correct dirs
     tmux new-window -t $SESSIONNAME:2 -n AR
     tmux new-window -t $SESSIONNAME:3 -n TR

     tmux split-window -h -t $SESSIONNAME:1.1
     tmux split-window -v -l 75% -t $SESSIONNAME:1.2
     tmux send-keys -t $SESSIONNAME:1.1 "cd $WORK_DIR; clear" Enter
     tmux send-keys -t $SESSIONNAME:1.2 "htop" Enter
     tmux send-keys -t $SESSIONNAME:1.3 "neofetch" Enter
     tmux select-pane -t 1.1
     
     
     tmux send-keys -t $SESSIONNAME:2 "cd $WORK_DIR/avtalsregister; clear" C-m
     tmux send-keys -t $SESSIONNAME:3 "cd $WORK_DIR/tjansteregister; clear" C-m
     
     tmux select-window -t $SESSIONNAME

fi

tmux attach -d -t $SESSIONNAME
