#! /bin/bash
set -x

hdmi_status=$(cat /sys/class/drm/card0-HDMI-A-1/status)
alsa_dir=/etc/alsa
asound_file=asound.hdmi-$hdmi_status

[[ -n $hdmi_status ]] \
    && [[ -f "$alsa_dir/$asound_file" ]] \
    && ln -svf "$alsa_dir/$asound_file" /etc/asound.conf \
    && /etc/rc.d/alsa force-restart
